# **Week 5  : Advanced Data Manipulation with Pandas**

# Project: Customer Sales Analysis

### Data loading and checking for missing values.

In [29]:
import pandas as pd

sales_df = pd.read_csv('sales_data.csv')
customer_df = pd.read_csv('customer_data.csv')

In [30]:
customer_df.head()

,CustomerID,CustomerName,Tenure,MonthlyCharges,TotalCharges,Contract,PaymentMethod,PaperlessBilling,SeniorCitizen,Churn
0,CUST-001,Samantha Anderson,52,83.76,4393.99,One year,Mailed check,No,0,Yes
1,CUST-002,Patricia Jimenez,15,108.72,1638.54,Month-to-month,Electronic check,Yes,1,Yes
2,CUST-003,Emily Young,72,67.22,4639.94,One year,Electronic check,No,1,Yes
3,CUST-004,Mark Moore,61,31.96,1822.64,Month-to-month,Credit card,No,0,Yes
4,CUST-005,Jack Wilson,21,91.32,2039.60,Month-to-month,Credit card,Yes,0,No

In [31]:
sales_df.head()

,Date,Product,Quantity,Price,Customer_ID,Region,Total_Sales
0,2025-06-04,Streaming Stick,5,49.99,CUST-004,West,249.95
1,2025-10-10,Security Camera,2,129.99,CUST-019,Central,259.98
2,2025-09-12,Tech Support,1,29.99,CUST-070,East,29.99
3,2025-08-08,Security Camera,4,129.99,CUST-098,Central,519.96
4,2025-05-07,Router Pro,4,89.99,CUST-082,West,359.96

because I planned to merge the 2 datset on customer id i want them two column name same.

In [32]:
sales_df = sales_df.rename(columns={'Customer_ID': 'CustomerID'})

In [33]:
print("Cheecking for Null values")
print(f'Sales dataset: \n')
print(sales_df.isna().sum())
print(f'\nCustomer dataset:\n')
print(customer_df.isna().sum())

Cheecking for Null values
Sales dataset:

Date           0
Product        0
Quantity       0
Price          0
CustomerID     0
Region         0
Total_Sales    0
dtype: int64

Customer dataset:

CustomerID          0
CustomerName        0
Tenure              0
MonthlyCharges      0
TotalCharges        0
Contract            0
PaymentMethod       0
PaperlessBilling    0
SeniorCitizen       0
Churn               0
dtype: int64

### Prepareing the data

I will merge this two dataset into using customer ID as common.

In [34]:
merged_df = sales_df.merge(customer_df,on='CustomerID')
merged_df.head()

,Date,Product,Quantity,Price,CustomerID,Region,Total_Sales,CustomerName,Tenure,MonthlyCharges,TotalCharges,Contract,PaymentMethod,PaperlessBilling,SeniorCitizen,Churn
0,2025-06-04,Streaming Stick,5,49.99,CUST-004,West,249.95,Mark Moore,61,31.96,1822.64,Month-to-month,Credit card,No,0,Yes
1,2025-10-10,Security Camera,2,129.99,CUST-019,Central,259.98,Christopher Patel,22,44.93,910.84,Two year,Electronic check,Yes,0,No
2,2025-09-12,Tech Support,1,29.99,CUST-070,East,29.99,George Lewis,24,87.21,2239.10,Month-to-month,Bank transfer,Yes,0,Yes
3,2025-08-08,Security Camera,4,129.99,CUST-098,Central,519.96,Anna Smith,62,45.79,2874.54,One year,Credit card,Yes,0,No
4,2025-05-07,Router Pro,4,89.99,CUST-082,West,359.96,Patrick Anderson,63,24.08,1482.93,Month-to-month,Electronic check,Yes,1,Yes

In [35]:
merged_df.shape

(500, 16)

In [36]:
mdf = merged_df.copy(deep=True)

Adding a Month_name Column

In [42]:
mdf['Date'] = pd.to_datetime(mdf['Date'])
mdf.head(1)

,Date,Product,Quantity,Price,CustomerID,Region,Total_Sales,CustomerName,Tenure,MonthlyCharges,TotalCharges,Contract,PaymentMethod,PaperlessBilling,SeniorCitizen,Churn
0,2025-06-04,Streaming Stick,5,49.99,CUST-004,West,249.95,Mark Moore,61,31.96,1822.64,Month-to-month,Credit card,No,0,Yes

In [45]:
mdf['monthname']= mdf['Date'].dt.month_name()
mdf.head(2)

,Date,Product,Quantity,Price,CustomerID,Region,Total_Sales,CustomerName,Tenure,MonthlyCharges,TotalCharges,Contract,PaymentMethod,PaperlessBilling,SeniorCitizen,Churn,monthname
0,2025-06-04,Streaming Stick,5,49.99,CUST-004,West,249.95,Mark Moore,61,31.96,1822.64,Month-to-month,Credit card,No,0,Yes,June
1,2025-10-10,Security Camera,2,129.99,CUST-019,Central,259.98,Christopher Patel,22,44.93,910.84,Two year,Electronic check,Yes,0,No,October

### Calculating Metrics:

In [48]:
monthly_performance = mdf.groupby('monthname')['Total_Sales']
print(monthly_performance)

<pandas.api.typing.SeriesGroupBy object at 0x0000026FB34E1E50>